[colors.primary]
background = "0x282327"
foreground = "0xCC8DD1"

[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Regular"

[window.padding]
x = 10
y = 10
